### ISSUE TITLE
Plugin works only with BigMemory product, not OSS Terracotta?

### ISSUE THREAD

**Issue by romanr** [Terracotta-OSS/terracotta-newrelic-plugin#15]
After spending some two hours trying to connect to my Terracotta instance without success I finally figured out that what mentioned as "TMC" is Terracotta Management Console. Some explanation would be a great time saver.

It says so in plugin requirements: "to be able to connect to TMC". TMC is not a part of Terracotta OSS. It's a part of BigMemory product.

Or am I missing something? Is it possible to run TMC without buying the commercial product? I wasn't able to find out how. Terracotta 4.3.0 contains directory "management-console" in tools. But it's completely different from "management-console" included in BigMemory. It does not have "start-tmc.sh" or anything that looks like an actual console.

If I am correct, the plugin should be removed as "Terracotta OSS " in listing as it is quite misleading. (The Plugin listed as two versions in NewRelic Plugin directory. Both versions are identical.)

**Comment by lanimall** [comment]
Hi yes apology on not being clear enough on that: this newrelic "plugin"
was built and tested against EE version of Terracotta. But since the
newrelic plugin itself is open source, that's why it ended up in this
listing.

That being said, having this work with 4.3.0 OSS was and still is on my
list of TODOs...so hopefully soon.

On Saturday, August 29, 2015, Roman Roan <notifications@github.com> wrote:

> After spending some two hours trying to connect to my Terracotta instance
> without success I finally figured out that what mentioned as "TMC" is
> Terracotta Management Console. Some explanation would be a great time saver.
>
> It says so in plugin requirements: "to be able to connect to TMC". TMC is
> not a part of Terracotta OSS. It's a part of BigMemory product.
>
> Or am I missing something? Is it possible to run TMC without buying the
> commercial product? I wasn't able to find out how. Terracotta 4.3.0
> contains directory "management-console" in tools. But it's completely
> different from "management-console" included in BigMemory. It does not have
> "start-tmc.sh" or anything that looks like an actual console.
>
> If I am correct, the plugin should be removed as "Terracotta OSS " in
> listing as it is quite misleading. (The Plugin listed as two versions in
> NewRelic Plugin directory. Both versions are identical.)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Terracotta-OSS/terracotta-newrelic-plugin/issues/15>.
>


-- 
Fabien Sanglier
fabiensanglier@gmail.com

**Comment by lanimall** [comment]
ok i tweaked the code a bit in the "tc_oss" branch, updated the documentation, and tested with 4.3.0 OSS and it worked fine for my local setup.
If you still want to try this out, it should work now. Please drop me a line if you have any question.
